spring:
  profiles:
    active: ${ext.profile}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com:
      appdong:
        website: DEBUG
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG